baseurl: '/'
permalink: pretty
title: 'Contentio - Lobby schermen voor uw appartementsgebouw'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/just-icon.png"
  desktop: "images/logo/logo-horizontal.png"
  desktop_height: "36px"

footer:
  copyright_text: 'Quodlibet BV <a class="zerostatic" href="https://quodlibet.be">quodlibet.be</a>'

seo:
  meta_og_title: "Lobby schermen voor uw appartementsgebouw - Contentio"
  meta_og_type: "website"
  meta_og_url: "https://contentio.be"
  //meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Contentio zorgt ervoor dat je een professioneel scherm in de lobby van je appartementsgebouw hebt, dat je prikbord of whiteboard vervangt.  Het kan eenvoudig worden onderhouden door de Conciërge, Syndicus of VME "
  //meta_twitter_card: "summary"
  //meta_twitter_site: "@zerostaticio"
  //meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
